import { StyleSheet, Platform } from 'react-native';
import { colors } from '../../utils/colors';

export { colors };

export default StyleSheet.create({
  conteiner: {
    flex: 1,
    backgroundColor: colors.background1,
  },
  barraSuperior: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: colors.background1,
  },
  tituloBarraSuperior: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '600',
    color: colors.textPrimary,
    letterSpacing: -0.3,
  },
  espacadorBarraSuperior: {
    width: 36,
  },
  conteinerCamera: {
    marginHorizontal: 20,
    marginBottom: 14,
    backgroundColor: '#0D0F1A',
    borderRadius: 20,
    overflow: 'hidden',
    height: 400,
    alignItems: 'center',
    justifyContent: 'center',
  },
  semPermissao: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0d0d1a',
    padding: 24,
  },
  textoSemPermissao: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 14,
    opacity: 0.7,
  },
  baseCanto: {
    position: 'absolute',
    width: 26,
    height: 26,
  },
  cantoSuperiorEsquerdo: {
    top: 20,
    left: 20,
    borderTopWidth: 2.5,
    borderLeftWidth: 2.5,
    borderColor: '#FFFFFF',
    borderTopLeftRadius: 6,
  },
  cantoSuperiorDireito: {
    top: 20,
    right: 20,
    borderTopWidth: 2.5,
    borderRightWidth: 2.5,
    borderColor: '#FFFFFF',
    borderTopRightRadius: 6,
  },
  cantoInferiorEsquerdo: {
    bottom: 20,
    left: 20,
    borderBottomWidth: 2.5,
    borderLeftWidth: 2.5,
    borderColor: '#FFFFFF',
    borderBottomLeftRadius: 6,
  },
  cantoInferiorDireito: {
    bottom: 20,
    right: 20,
    borderBottomWidth: 2.5,
    borderRightWidth: 2.5,
    borderColor: '#FFFFFF',
    borderBottomRightRadius: 6,
  },
  sobreposicaoEscaneado: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    right: 16,
    backgroundColor: 'rgba(0,0,0,0.75)',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    gap: 8,
  },
  textoEscaneado: {
    color: '#fff',
    fontSize: 13,
    textAlign: 'center',
  },
  botaoNovaLeitura: {
    backgroundColor: '#fff',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  textoNovaLeitura: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0d0d1a',
  },
  dicaLeitura: {
    position: 'absolute',
    bottom: 16,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 12,
    color: 'rgba(255,255,255,0.45)',
  },
  espacadorVertical: {
    marginVertical: 5,
  },
  cartaoOpcao: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
    marginHorizontal: 20,
    marginBottom: 8,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  conteinerOpcaoEsquerda: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  envolturaIconeOpcao: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconeOpcao: {
    borderRadius: 11,
  },
  rotuloOpcao: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 2,
  },
  subtituloOpcao: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  botaoAlternador: {
    width: 44,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    paddingHorizontal: 3,
    alignItems: 'flex-end',
  },
  botaoAlternadorDesligado: {
    backgroundColor: colors.border,
    alignItems: 'flex-start',
  },
  pontoAlternador: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  iconeSeta: {
    fontSize: 18,
    color: colors.textHint,
  },
  // Modal Styles
  modalSobreposicao: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'flex-end',
  },
  modalConteudo: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
  },
  modalTitulo: {
    fontSize: 17,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  modalSubtitulo: {
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: 16,
  },
  modalInput: {
    backgroundColor: colors.background1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: colors.textPrimary,
    marginBottom: 16,
  },
  modalBotaoPrincipal: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  modalTextoBotaoPrincipal: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 15,
  },
  modalBotaoCancelar: {
    marginTop: 12,
    alignItems: 'center',
  },
  modalTextoBotaoCancelar: {
    color: colors.textSecondary,
    fontSize: 14,
  },
});
