import { StyleSheet } from 'react-native';
import { colors } from '../../utils/colors';

export default StyleSheet.create({
  barraSuperior: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: colors.background1,
  },
  tituloBarraSuperior: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '600',
    color: colors.textPrimary,
    letterSpacing: -0.3,
  },
  espacadorBarraSuperior: {
    width: 36,
  },
  conteinerCamera: {
    marginHorizontal: 20,
    marginBottom: 14,
    backgroundColor: '#0D0F1A',
    borderRadius: 20,
    overflow: 'hidden',
    height: 400,
    alignItems: 'center',
    justifyContent: 'center',
  },
  semPermissao: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0d0d1a',
    padding: 24,
  },
  textoSemPermissao: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 14,
    opacity: 0.7,
  },
  baseCanto: {
    position: 'absolute',
    width: 26,
    height: 26,
  },
  cantoSuperiorEsquerdo: {
    top: 20,
    left: 20,
    borderTopWidth: 2.5,
    borderLeftWidth: 2.5,
    borderColor: '#FFFFFF',
    borderTopLeftRadius: 6,
  },
  cantoSuperiorDireito: {
    top: 20,
    right: 20,
    borderTopWidth: 2.5,
    borderRightWidth: 2.5,
    borderColor: '#FFFFFF',
    borderTopRightRadius: 6,
  },
  cantoInferiorEsquerdo: {
    bottom: 20,
    left: 20,
    borderBottomWidth: 2.5,
    borderLeftWidth: 2.5,
    borderColor: '#FFFFFF',
    borderBottomLeftRadius: 6,
  },
  cantoInferiorDireito: {
    bottom: 20,
    right: 20,
    borderBottomWidth: 2.5,
    borderRightWidth: 2.5,
    borderColor: '#FFFFFF',
    borderBottomRightRadius: 6,
  },
  sobreposicaoEscaneado: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    right: 16,
    backgroundColor: 'rgba(0,0,0,0.75)',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    gap: 8,
  },
  textoEscaneado: {
    color: '#fff',
    fontSize: 13,
    textAlign: 'center',
  },
  botaoNovaLeitura: {
    backgroundColor: '#fff',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  textoNovaLeitura: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0d0d1a',
  },
  dicaLeitura: {
    position: 'absolute',
    bottom: 16,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 12,
    color: 'rgba(255,255,255,0.45)',
  },
});