export const colors = {
  background1: '#F5F6FA',
  backgroundtop: '#0B56C5',
  surface: '#FFFFFF',
  primary: '#0B56C5',
  secondary: "#1E73E8",
  primaryLight: '#E8EAF6',
  textPrimary: '#0D0F1A',
  textSecondary: '#6B7080',
  textHint: '#A8AEBC',
  border: '#E8EAF0',
  success: '#1B8A5A',
  successBg: '#E6F5EE',
  warning: '#C07A00',
  warningBg: '#FFF3DC',
  tabActive: '#EDF5FF',
  tabInactive: '#A8AEBC',
};
