export const colors = {
  background1:    '#F5F6FA',
  backgroundDark: '#111827',
  backgroundtop:  '#0B56C5',
  surface:        '#FFFFFF',
  primary:        '#0B56C5',
  secondary:      '#1E73E8',
  primaryLight:   '#E8EAF6',
  accent:         '#818CF8',
  textPrimary:    '#0D0F1A',
  textSecondary:  '#6B7080',
  textHint:       '#A8AEBC',
  textOnDark:     '#F9FAFB',
  border:         '#E8EAF0',
  success:        '#07e18a',
  successBg:      '#E6F5EE',
  warning:        '#fda200',
  warningBg:      '#FFF3DC',
  tabActive:      '#EDF5FF',
  tabInactive:    '#A8AEBC',
};
